// Mock data for listing; swap with API later
import { Mentor } from '@/types/mentor';

export const mentors: Mentor[] = [
    {
        id: 'sid-1',
        name: 'Siddhant Jain',
        title: 'Senior Software Engineer',
        company: 'TechNova',
        avatar: '/images/avatars/1.png',
        expertise: ['React', 'Next.js', 'System Design', 'Interview Prep'],
        rating: 4.9,
        totalSessions: 128,
        pricePerSession: 49,
        bio: 'Frontend specialist helping devs master React/Next, prepare for FAANG-style interviews, and ship performant UIs.',
        yearsOfExperience: 8,
    },
    {
        id: 'sam-2',
        name: 'Abdul Samad Kirmani',
        title: 'Software Developer',
        company: 'DevWorks',
        avatar: '/images/avatars/2.png',
        expertise: ['Node.js', 'TypeScript', 'APIs', 'Career Guidance'],
        rating: 4.8,
        totalSessions: 94,
        pricePerSession: 39,
        bio: 'Backend and API design mentor with strong TypeScript focus. Pragmatic guidance for real-world systems.',
        yearsOfExperience: 6,
    },
    {
        id: 'priya-3',
        name: 'Priya Sharma',
        title: 'Product Manager',
        company: 'Acme Product',
        avatar: '/images/avatars/3.png',
        expertise: ['Product Management', 'Roadmaps', 'UX', 'Interviews'],
        rating: 4.9,
        totalSessions: 210,
        pricePerSession: 59,
        bio: 'PM mentor helping engineers transition into product, with strong emphasis on problem discovery and UX.',
        yearsOfExperience: 9,
    },
    {
        id: 'alex-4',
        name: 'Alex Chen',
        title: 'Full-Stack Engineer',
        company: 'ScaleUp',
        avatar: '/images/avatars/4.png',
        expertise: ['Full-Stack', 'Performance', 'Cloud', 'Databases'],
        rating: 4.7,
        totalSessions: 75,
        pricePerSession: 45,
        bio: 'Full-stack mentor focused on performance, reliability, and clean architectures for growing products.',
        yearsOfExperience: 7,
    },
    {
        id: 'nina-5',
        name: 'Nina Patel',
        title: 'Data Engineer',
        company: 'Insightful',
        avatar: '/images/avatars/5.png',
        expertise: ['Data Engineering', 'SQL', 'ETL', 'Interview Prep'],
        rating: 4.8,
        totalSessions: 60,
        pricePerSession: 55,
        bio: 'Data mentor helping you build robust pipelines, ace DE interviews, and write production-grade SQL.',
        yearsOfExperience: 6,
    },
];
